# Viena vieta, kur susitariat dėl "type" pavadinimų

TYPE_JOIN = "join"
TYPE_JOIN_OK = "join_ok"
TYPE_START = "start"
TYPE_START_OK = "start_ok"
TYPE_ANSWER = "answer"
TYPE_ANSWER_ACK = "answer_ack"
TYPE_QUESTION = "question"
TYPE_ROUND_END = "round_end"
TYPE_NEXT_IN = "next_in"
TYPE_GAME_OVER = "game_over"
TYPE_SCOREBOARD = "scoreboard"
TYPE_PLAYERS = "players"
TYPE_ERROR = "error"
TYPE_EXIT = "exit"
TYPE_BYE = "bye"
